### ISSUE TITLE
Add Faceting Functionality

### ISSUE THREAD

**Issue by oliverheywood451** [ordercloud-api/ngx-shopper#114]
This feature relies on bleeding edge API  functionality so make sure those endpoints are ready before starting this issue. (Ask Todd)

Formal Requirements can be established closer to the date of implementation. The general idea is filtering product lists.
- A list of facet values on a left nav with a sub list of options for each.
- The options each have a checkbox and when the checkbox is activated, only products that match that option are displayed.
- Info about quantities next to the options.

(Note - not required for Archway)

Link to Details on Facets in OC - https://docs.google.com/document/d/1DC6GaPagpdjx5dOLZloND4olSIQCCYWtGzrMrIFRd58/edit

**Comment by crhistianramirez** [comment]
Link to API feature on Jira - https://four51.atlassian.net/browse/EX-1624

**Comment by oliverheywood451** [comment]
Note for QA - leave this alone until we have a chance to talk about it. You won't see it in the hosted sites because it is not an Archway feature.
