### ISSUE TITLE
View-Only products

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#13]
As a buyer user I should be able to browse products that can't be ordered. A product is considered view-only if it does not have a price schedule 

Acceptance Criteria:
-  I should not be able to add this product to my cart anywhere in the app: product list, product detail
-  On the product list page instead of Add To Cart I should see "View Product", which takes me to the product detail page
-  On the product detail page I should not see an add to cart button, instead I should see an info-alert stating I am not able to order this product

**Comment by lisajtanner** [comment]
Updating user story to only be view-only if it doesn't have a price schedule -  a buyer should be able to add  a product with $0 to the cart.
