### ISSUE TITLE
Change password on profile component

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#143]
As a buyer user I should be able to change my password while logged in.

Note: you can currently change your password by using the "forgot password" flow on login page if you need to until this is implemented

Acceptance Criteria:
* I should have to confirm my current password
*  I should have to enter my new password twice
*  Logging in after changing password should require me to enter my new password
*  I should only be able to enter a valid password - at least 8 characters long and at least one letter and one number

**Comment by yb0rc1ty** [comment]
@crhistianramirez I was able to create a new password via the Forgot Password flow that was only numbers and special characters -- "12345678!"

We need to make sure that passwords for at least one number and one letter.
