### ISSUE TITLE
Unable to view Favorite Products in mobile view

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#152]
When browsing the site on a mobile device, I am unable to view my favorite products. This bug was discovered using the Safari browser on an iPhone.

**Comment by Labedlam** [comment]
@crhistianramirez  Ill have a fix for this in the product browse mobile view

**Comment by crhistianramirez** [comment]
Ok sounds good. I'll assign it to you then
