### ISSUE TITLE
Search content remains after navigation away from search results

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#164]
Steps to recreate:
Log in 
Enter "hose" into search bar, click ENTER
From search results page, click on any category or on "Browse Products"
Notice that the content in the search bar remains in there

This is confusing for the customer. We should empty the search bar once you move away from the search results.

**Comment by crhistianramirez** [comment]
I agree that clicking 'Browse Products' or 'All Products' should clear search bar but it might make sense to keep it in there if they click in a category.

For example I might want to go into category and further filter my result set by the name of a brand or something.

**Comment by yb0rc1ty** [comment]
@crhistianramirez That makes sense to me. I think that is going to be the best way to go about this.
