### ISSUE TITLE
"View Product" button on View Only Products causes error, does not bring you to product detail page

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#168]
Steps to recreate:
Log-in to base buyer app
Navigate to Browse Products
Find a View Only Product in the product list
Attempt to click on "View Product"

You'll see a toastr error that reads "_co.toProductDetails is not a function". The console throws the same error, no network tab errors.

Conversely, if you click on the product image, you are brought to the product detail page without issue. The only problem is with the button. 
![base app 3](https://user-images.githubusercontent.com/12968164/44727856-9d93d280-aaa0-11e8-952d-56e60d25fc70.png)

**Comment by crhistianramirez** [comment]
I'm unable to recreate this error. These were the exact steps I took, please test again and verify this is working.

1. Log in as test buyer (pw: fails345)
2. Navigate to product-browse
3.  Click 'View Product' on ProductID 11542 (Commercial 5' - Filler Hose)
