### ISSUE TITLE
Limit # of products that can be favorited

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#169]
As a buyer user I should not be able to favorite more than 50 products.  This ensures that user.xp is not overwhelmed and can be used for other features.

Acceptance Criteria:
* If I reach the limit I should get a toaster that says I can not have more than 50 favorite products

Additional Notes: lets make sure we're chunking out the filter list call to whatever the pagesize is. So if we have pageSize 25 the filter for our list call should have at most 25 ID's OR'd together.

**Comment by oliverheywood451** [comment]
Exact same functionality needed for favorite addresses.
