### ISSUE TITLE
Seller -- Removing or changing an address ID is not reflected in the address after saving changes

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#185]
Steps to recreate:
Log into seller app
Create a new address in address management
Notice that Address ID is optional -- if you do not enter an ID, the ID will appear as a random string of characters
Once your address is created, attempt to remove or change the address ID -- since the ID field is optional, you should be able to do either of those things.
Those changes are not saved to the address after saving the address.

**Comment by oliverheywood451** [comment]
Same issue with users.

**Comment by yb0rc1ty** [comment]
AW says that User Groups works as expected with regards to IDs. That should be the template.
