### ISSUE TITLE
Saving changes in user profile (buyer) changes username to email address (seller)

### ISSUE THREAD

**Issue by yb0rc1ty** [ordercloud-api/ngx-shopper#186]
Steps to recreate:
Create a new user in the seller application -- make sure that the username is different than the email address
Log in as that user in the buyer app
Navigate to the users profile, review the profile information without changing anything and click "Save"
Go back to the seller app and look for that user via search
The user's username will have changed to the email address

**Comment by crhistianramirez** [comment]
We had previously been tying Username to Email because we were building this off  of a client-specific solution at first. In addition to those fields no longer being coupled I'm exposing the editing of Username on the buyer app. That  is a very natural thing to want to change as a buyer
