### ISSUE TITLE
"Add to Cart" should be "Update Cart" for products in the cart.

### ISSUE THREAD

**Issue by oliverheywood451** [ordercloud-api/ngx-shopper#195]
If a product has been added to the cart, then the button "Add to Cart" on both the product list page and product details page should read "Update Cart" and the default quantity next to the button should be the quantity currently in the cart. 

On product detail this will also affect the price shown on the button, which should default to the quantity in the cart times the correct price.

The green pop-up when an item is added to the cart should also change. Instead of reporting the number of items added to the cart, it should report the total number of that product in the cart after the update.

Thanks Milind Patil.

**Comment by Labedlam** [comment]
@oliverheywood451 , if your in the product list or product detail page and modify the quantity, then click update cart, is it suppose to function as if changing the quantity in the cart?
