### ISSUE TITLE
Address Search not working 

### ISSUE THREAD

**Issue by patil-milind** [ordercloud-api/ngx-shopper#245]
Steps to recreate: 
1. Go to Profile 
2. Navigate to address 
3. In Address search box enter search criteria 

Expected:
Address should be filter out as per the enter search criteria.

**Comment by amrarick26** [comment]
@patil-milind can you please provide the criteria you are searching on? For example, are you searching on City, State, Street1, etc.?

**Comment by patil-milind** [comment]
@amrarick26  You can close this. Its working now. I have posted this long back.

**Comment by crhistianramirez** [comment]
Issue is resolved
