### ISSUE TITLE
Payment Method Validating

### ISSUE THREAD

**Issue by lisajtanner** [ordercloud-api/ngx-shopper#267]
1) Card Holder# - should be number and space only (can this be limited to 20 chars?)
 2) Card Holder Name - should be only alpha numeric with spaces and special characters "-“, “apostrophe”, and “.”
3) CCV should be number only (limit the characters to 4 characters – 3 for MC, Visa and Discover; 4 for Amex)

**Comment by oliverheywood451** [comment]
I've added these requirements to Issue #28, Pay With Credit Card so they will be visible when that task is picked up. I'm going to close this issue.
