### ISSUE TITLE
Prevent buyer users from submitting order multiple times 

### ISSUE THREAD

**Issue by lisajtanner** [ordercloud-api/ngx-shopper#293]
Archway experience a situations where a buyer was able to submit the same order twice which triggered the submit order web hook twice.  We were able to recreate a scenario where this was possible by logging into the buyer app, adding something to the cart and moving through to the submit order screen of checkout without clicking submit order - and then opening another tab, logging into the same account and checking out through to order submit - and then going back to the original checkout and submitting order.

Action:  add code to check to see if the order has already been submitted before submitting the order.  If the order has been submitted, create custom message to buyer saying that the order has already been submitted.

**Comment by crhistianramirez** [comment]
This is resolved
