### ISSUE TITLE
Favorite Orders <3

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#30]
As a buyer user I'd like to be able to save orders that I place frequently in order to be able to quickly reorder

Acceptance Criteria:
- I should be able to click this heart icon to mark an order as favorite
- I should be able to filter orders in order history to view my favorite orders
- i should be able to mark an order as favorite from the order history page
- i should be able to mark an order as favorite from the order detail page

**Comment by lisajtanner** [comment]
I don't see the ability to mark an order as a favorite from the order detail page  (last acceptance criteria)
