### ISSUE TITLE
Order History

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#38]
As a buyer user I would like a section of the app to browse orders I have placed and use a variety of filters to quickly find an order.

Acceptance Criteria:
- filters on the order history page are cumulative meaning if another filter already exists and I add a new filter, both filters must be satisfied
- I should be able to search for order by orderID (partial & full)
- I should be able to clear search by removing text in search box
- I should be able to select a From Date using a datepicker and get a list of orders that have been placed after that date
- I should be able to clear FromDate filter by clearing text in FromDate
- I should be able to select a To Date using a datepicker and get a list of orders that have been placed before that date
- I should be able to clear ToDate filter by clearing text in ToDate
- I should be able to select a status from a dropdown and filter the list of orders by that status
- I should be able to clear status filter by selecting All from dropdown
- I should be able to see the following details about an order:
    - `ID`
    - `Status`
    -  `DateSubmitted`
    -  `Total`

**Comment by lisajtanner** [comment]
Change to Critieria -

 I should be able to select a From Date using a datepicker and get a list of orders that have been placed after that date **inclusive of the date selected**

I should be able to select a To Date using a datepicker and get a list of orders that have been placed before that date **inclusive of the date selected**
