### ISSUE TITLE
Product Detail

### ISSUE THREAD

**Issue by crhistianramirez** [ordercloud-api/ngx-shopper#46]
As a buyer user I'd like to get more detail about a specific product before adding it to my cart

Located: Product List > Product Detail

Acceptance Criteria:
- I should be able to add the currently viewed product to my cart(#15)
- I should be able to see all of the images associated with this product(#45)
- I should be able to favorite a product(#14)
- I should only be able to order in certain quantities if `RestrictedQuantity` is set on the price schedule 
- I should be able to view product Description

**Comment by lisajtanner** [comment]
I am not sure why Price/Total price is not included in the product detail.  

Also, just a little thing - but when hovering over the image, the magnifying window pops up.  By moving the cursor off the picture, the magnifying window goes away except when you move out of the image to the right bottom over the description.
