### ISSUE TITLE
Add Category Selection Indicator  

### ISSUE THREAD

**Issue by lisajtanner** [ordercloud-api/ngx-shopper#89]
![image](https://user-images.githubusercontent.com/20684161/43021091-09cd5d64-8c28-11e8-9d10-d575aef40b97.png)

Indicator doesn't change when selecting a new category - and stays on "Hoses" when "All Product" selected

**Comment by crhistianramirez** [comment]
The issue looks good. Love the image - that stuff is super helpful. For this specific one, the arrow isn't a selection indicator, it means there are sub-categories. We probably do need some selection indicator styling though.

**Comment by crhistianramirez** [comment]
Maybe we can change this to possible enhancement?

**Comment by lisajtanner** [comment]
Changed name and added to to Enhancements
