### ISSUE TITLE
Improve Add to Cart Indicators 

### ISSUE THREAD

**Issue by lisajtanner** [ordercloud-api/ngx-shopper#92]
When Adding Item to cart for the first time, there is a pop-up indicating that an item has been added.  If the same item is added again to the cart there isn't any pop-up indicating that that something changed.  
After an item has been added, the quantity should be reset to 1 - as another indicator that the item was added.

**Comment by patil-milind** [comment]
Once the Item Added to Cart the label should also change to "Update Cart" from "Add to Cart" and the Item quantity need to be same as current quantity in cart.

**Comment by oliverheywood451** [comment]
Cleaning up old stuff here. I think patil-milind's suggestion has advantages. The user can see what is in the cart from the Product Details page. Thoughts?

**Comment by crhistianramirez** [comment]
Yeah, that sounds good to me. Let's plan on doing that as a separate task because it looks like Lisa's suggestions are already implemented

**Comment by oliverheywood451** [comment]
I'll create a new issue.
