### ISSUE TITLE
Better Indication for Clickable Link

### ISSUE THREAD

**Issue by lisajtanner** [ordercloud-api/ngx-shopper#93]
There is a cursor rather than a "hand" to indicate that there is a clickable link in the following places:

- Order List page (under My Profile/Order) - when hovering over Order ID
- Featured Products (on home page) - when hovering over Product Name or Image
- Product List Page - when hovering over Product Name or Image

**Comment by crhistianramirez** [comment]
I have an open PR addressing this issue and have updated all clickable elements to be styled as such however the product card which is used by both the featured products and product list now only has the image as a clickable link. 

This was a design decision introduced in this PR - https://github.com/ordercloud-api/ngx-shopper/pull/90

**Comment by yb0rc1ty** [comment]
@oliverheywood451 I'm not seeing this issue as resolved. In Order History, I still see a cursor. And there is no discernible difference to either featured products or product list. Has this PR been deployed?
